### ISSUE TITLE
Link not working in the page

### ISSUE THREAD

**Issue by pavansarma93** [MicrosoftDocs/powerapps-docs#1792]
Hi Team,

In the page at

> For more information about actions, see Use actions

The link is not working. It is referring to [https://docs.microsoft.com/en-us/flow/actions](url) which is no longer available. Also it would be helpful if a sample is provided on the page.

Thanks in advance
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a261db5-f03e-8100-f9b9-592ba9a34cea
* Version Independent ID: 281480d2-01b3-1488-9f00-9e82fd6d93ef
* Content: [invokeProcessAction (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/invokeprocessaction?source=docs)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/invokeProcessAction.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/invokeProcessAction.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@pavansarma93  Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

**Comment by pavansarma93** [comment]
@Nkrb : Though the link is available an example on implementation would be helpful similar to [https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/retrieverecord](url) , because when tried as per documentation I am still getting errors
