### ISSUE TITLE
Success Callback Parameter

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/powerapps-docs#834]
The sample code specifies a "result" parameter in the success callback, but no information is present in the successCallback function description.

If this parameter is used, please include a description of the value(s) passed into it. If it is not used, please remove it from the sample code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d991c0b4-ff31-84e2-4084-f2ef82d77588
* Version Independent ID: ad7a366f-8d17-82f5-ea6e-c5feee2545cf
* Content: [openAlertDialog (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openalertdialog)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openAlertDialog.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openAlertDialog.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@devlinl Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

**Comment by devlinl** [comment]
It appears as though you simply changed the name of the parameter from “result” to “success”.

The problem was not the name of the object, it was the fact that there is no information on what this object is.

There is still no information on what this object is in the description of successCallback.

Thanks,

Liam Devlin
Senior Architect, Microsoft Dynamics Higher Education
Liam@xRM.com<mailto:Liam@xRM.com>
725-696-7234
xRM<xrm.com> | NexGen Advancement Solutions

**Comment by KendalBond007** [comment]
Thanks for contacting us. As noted previously, the doc has been updated per Nkrb in 2020. Closing this issue.

**Comment by devlinl** [comment]
Okay, but as I noted in 2020, the update didn't actually address the issue I was raising.

This document's sample code still shows an object being passed into both the closeCallback and errorCallback functions, but provides no descriptions of those objects.

**Comment by darshSWL** [comment]
This issue is still open after four years?

The parameter in the success callback is just an empty object.
The parameter in the error callback seems to be a normal Error object.

Would it be possible to add this information to the Parameters table (Description)?
